/// Source of the golden guard snippet printed by
/// `crap_dart goldens --print-snippet` and documented in the README.
///
/// The snippet lives here as a string (not compiled library code)
/// because it depends on `flutter_test`, which a pure-Dart package
/// cannot depend on. Projects copy it into `test/` (typically
/// `test/goldens_guard.dart`) and wrap their golden tests with it.
///
/// Scope: the guard catches STANDARD image loading failures
/// (`Image.asset`/`Image.network` reporting through FlutterError).
/// Widgets that render their own fallback icons on failure (custom
/// errorBuilder paths, e.g. `Icon(Icons.broken_image)`) emit no error
/// — for those, the `broken_goldens` gate's pixel detector is the only
/// witness.
const String goldenGuardSnippet = r'''
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';

/// Fails the test when any image-resource error fires inside [body] —
/// the exact cases where Flutter renders a tofu placeholder (box with
/// an X) into the golden while keeping the test green.
///
/// Generated by `crap_dart goldens --print-snippet`.
Future<void> guardGoldens(
  WidgetTester tester,
  Future<void> Function() body,
) async {
  final failures = <String>[];
  final previousError = FlutterError.onError;
  final previousPrint = debugPrint;
  FlutterError.onError = (details) {
    final text = '${details.exception}\n${details.context ?? ''}';
    if (details.library == 'image resource service' ||
        _imageErrorPatterns.any(text.contains)) {
      failures.add('${details.exception}');
    }
    previousError?.call(details);
  };
  debugPrint = (String? message, {int? wrapWidth}) {
    final text = message ?? '';
    if (_imageErrorPatterns.any(text.contains)) failures.add(text);
    previousPrint(message, wrapWidth: wrapWidth);
  };
  try {
    await body();
  } finally {
    FlutterError.onError = previousError;
    debugPrint = previousPrint;
  }
  expect(
    failures,
    isEmpty,
    reason: 'image loading failed during the golden — the snapshot would '
        'contain a broken icon placeholder:\n'
        '${failures.join('\n')}',
  );
}

const List<String> _imageErrorPatterns = [
  'Unable to load asset',
  'HTTP request failed',
  'Invalid image data',
  'image resource service',
];
''';
